---
name: monster-ui-application-voicemails
base_branch: 'origin/5.1'
exposure: private
metapackage:
  - name: meta-monster-ui
    branch: '5.1'
    package: monster-ui-application-voicemails
    type: required
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  centos7:
    name: monster-ui-application-voicemails
    app_name: voicemails
    license: "MPL 2.0"
    group: Productivity/Telephony
    url: http://www.2600hz.org/
    vendor: 2600Hz
